import {
    Squares2X2Icon,
    BookOpenIcon,
    VideoCameraIcon,
    DocumentTextIcon,
    ChartBarIcon,
    QuestionMarkCircleIcon,
    ChatBubbleLeftRightIcon,
    BuildingLibraryIcon,
    TrophyIcon,
    UsersIcon,
    AcademicCapIcon,
    BanknotesIcon,
    CalendarIcon,
    RectangleStackIcon,
    IdentificationIcon,
    MegaphoneIcon,
    CalendarDaysIcon,
    Cog6ToothIcon,
    ClipboardDocumentCheckIcon,
    AcademicCapIcon as CompetencyIcon,
    FolderOpenIcon,
    DocumentChartBarIcon
} from "@heroicons/react/24/solid";

export type Role = "student" | "parent" | "teacher" | "admin";

export const NAVIGATION_LINKS = {
    student: [
        { name: "Dashboard", href: "/student", icon: Squares2X2Icon },
        { name: "My Courses", href: "/student/courses", icon: BookOpenIcon },
        { name: "Live Lessons", href: "/student/lessons", icon: VideoCameraIcon },
        { name: "Competencies", href: "/student/competencies", icon: ChartBarIcon },
        { name: "Assignments", href: "/student/assignments", icon: DocumentTextIcon },
        { name: "Inbox", href: "/student/inbox", icon: ChatBubbleLeftRightIcon },
        { name: "Grades", href: "/student/grades", icon: ChartBarIcon },
        { name: "Reports", href: "/student/reports", icon: DocumentChartBarIcon },
        { name: "Quizzes", href: "/student/quizzes", icon: QuestionMarkCircleIcon },
        { name: "Forums", href: "/forums", icon: ChatBubbleLeftRightIcon },
        { name: "Library", href: "/student/library", icon: BuildingLibraryIcon },
        { name: "Achievements", href: "/student/achievements", icon: TrophyIcon },
    ],
    parent: [
        { name: "Overview", href: "/parent", icon: Squares2X2Icon },
        { name: "My Children", href: "/parent/children", icon: UsersIcon },
        { name: "Teachers", href: "/parent/teachers", icon: AcademicCapIcon },
        { name: "Fees & Payments", href: "/parent/finance", icon: BanknotesIcon },
        { name: "Schedule", href: "/parent/schedule", icon: CalendarIcon },
        { name: "Messages", href: "/parent/messages", icon: ChatBubbleLeftRightIcon },
        { name: "Forums", href: "/forums", icon: ChatBubbleLeftRightIcon },
    ],
    teacher: [
        { name: "Dashboard", href: "/teacher", icon: Squares2X2Icon },
        { name: "Courses", href: "/teacher/courses", icon: BookOpenIcon },
        { name: "Lessons", href: "/teacher/lessons", icon: VideoCameraIcon },
        { name: "Assessments", href: "/teacher/assessments", icon: ClipboardDocumentCheckIcon },
        { name: "Portfolio", href: "/teacher/portfolio", icon: FolderOpenIcon },
        { name: "Reports", href: "/teacher/reports", icon: DocumentChartBarIcon },
        { name: "Attendance", href: "/teacher/attendance", icon: CalendarIcon },
        { name: "Grades", href: "/teacher/grades", icon: ChartBarIcon },
        { name: "Messages", href: "/teacher/messages", icon: ChatBubbleLeftRightIcon },
        { name: "Earnings", href: "/teacher/earnings", icon: BanknotesIcon },
        { name: "Forums", href: "/forums", icon: ChatBubbleLeftRightIcon },
    ],
    admin: [
        { name: "Admin Panel", href: "/admin", icon: Squares2X2Icon },
        { name: "Users", href: "/admin/users", icon: UsersIcon },
        { name: "Cohorts", href: "/admin/cohorts", icon: RectangleStackIcon },
        { name: "Teachers", href: "/admin/teachers", icon: IdentificationIcon },
        { name: "CBC Analytics", href: "/admin/analytics", icon: ChartBarIcon },
        { name: "Finance", href: "/admin/finance", icon: BanknotesIcon },
        { name: "Calendar", href: "/admin/calendar", icon: CalendarDaysIcon },
        { name: "Announcements", href: "/admin/announcements", icon: MegaphoneIcon },
        { name: "Forums", href: "/forums", icon: ChatBubbleLeftRightIcon },
        { name: "Settings", href: "/admin/settings", icon: Cog6ToothIcon },
    ]
};
